import { IProduct, IRelease } from "@/interfaces";

export const productsMock: IProduct[] = [
  {
    id: "1",
    name: "Jaqueta Moletom Corinthians Print Preta",
    image_url: "/images/mock/man1.png",
    slug: "jaqueta-moletom-corinthians-print-preta",
    price: 481.00,
    size: "G",
    gender: "male",
    description: "Leve o seu orgulho aos estádios com a camisa I da Alemanha 2024, feita pela Adidas, é uma peça superleve que enche o seu coração com o DNA alemão. O manto é feito em poliéster, exibe design nas cores branca e preta, além de o nome do país `Deutschland` na nuca",
    isRate: false,
    category_id: "",
    subcategory_id: "",
    catalog_meta: "",
    supplier_id: "",
    url: "",
    createdAt: undefined,
    updatedAt: undefined,
    deletedAt: null,
    category: null,
    rateProduct: [],
    subcategory: null,
    productImages: [],
    brands: [],
    images: [],
    un: "",
    modelo: "",
    cor: "",
    tonalidade: "",
    pesoLiq: 0,
    pesoBruto: 0,
  },
  {
    id: "2",
    name: "Jaqueta Moletom Corinthians Print Preta",
    image_url: "/images/mock/woman1.png",
    price: 50,
    description: "",
    isRate: false,
    category_id: "",
    subcategory_id: "",
    catalog_meta: "",
    supplier_id: "",
    url: "",
    slug: "",
    createdAt: undefined,
    updatedAt: undefined,
    deletedAt: null,
    category: null,
    rateProduct: [],
    subcategory: null,
    productImages: [],
    brands: [],
    images: [],
    un: "",
    modelo: "",
    cor: "",
    tonalidade: "",
    pesoLiq: 0,
    pesoBruto: 0,
  },
  {
    id: "3",
    name: "Jaqueta Moletom Corinthians Print Preta",
    image_url: "/images/mock/man1.png",
    price: 70,
    description: "",
    isRate: false,
    category_id: "",
    subcategory_id: "",
    catalog_meta: "",
    supplier_id: "",
    url: "",
    slug: "",
    createdAt: undefined,
    updatedAt: undefined,
    deletedAt: null,
    category: null,
    rateProduct: [],
    subcategory: null,
    productImages: [],
    brands: [],
    images: [],
    un: "",
    modelo: "",
    cor: "",
    tonalidade: "",
    pesoLiq: 0,
    pesoBruto: 0,
  },
  {
    id: "4",
    name: "Jaqueta Moletom Corinthians Print Preta",
    image_url: "/images/mock/woman1.png",
    price: 10,
    description: "",
    isRate: false,
    category_id: "",
    subcategory_id: "",
    catalog_meta: "",
    supplier_id: "",
    url: "",
    slug: "",
    createdAt: undefined,
    updatedAt: undefined,
    deletedAt: null,
    category: null,
    rateProduct: [],
    subcategory: null,
    productImages: [],
    brands: [],
    images: [],
    un: "",
    modelo: "",
    cor: "",
    tonalidade: "",
    pesoLiq: 0,
    pesoBruto: 0,
  },
  {
    id: "5",
    name: "Jaqueta Moletom Corinthians Print Preta",
    image_url: "/images/mock/woman1.png",
    price: 10,
    description: "",
    isRate: false,
    category_id: "",
    subcategory_id: "",
    catalog_meta: "",
    supplier_id: "",
    url: "",
    slug: "",
    createdAt: undefined,
    updatedAt: undefined,
    deletedAt: null,
    category: null,
    rateProduct: [],
    subcategory: null,
    productImages: [],
    brands: [],
    images: [],
    un: "",
    modelo: "",
    cor: "",
    tonalidade: "",
    pesoLiq: 0,
    pesoBruto: 0,
  },
];

export const categoriesMock = [
  {
    id: 1,
    name: "Seção feminina",
  },
  {
    id: 2,
    name: "Seção infantil",
  },
  {
    id: 3,
    name: "Coleção jogador",
  },
  {
    id: 4,
    name: "Coleção Torcedor",
  },
];

export const collectionsMock = [
  {
    id: 1,
    name: "Clubes Brasileiros",
    image_url: "/images/banners/collection1.png",
  },
  {
    id: 2,
    name: "Clubes Europeus",
    image_url: "/images/banners/collection2.png",
  },
  {
    id: 3,
    name: "Mantos da Seleção",
    image_url: "/images/banners/collection3.png",
  },
];
